version: '3.8'

services:
  blip-luma-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static/videos:/app/static/videos
    env_file:
      - .env
    restart: unless-stopped
